### ISSUE TITLE
feat: API 연결 Check-list

### ISSUE THREAD

**Issue by PortalCube** [Hallym-LIKELION/HallymFestival2023-Frontend#37]
# TODO

### STEP1. api-client.js에 명세서대로 구현하기
- [x] 기타
  - [x] GET 아이피 가져오기
- [x] 부스
  - [x] GET 부스 목록 조회
  - [x] GET 부스 상세 조회
  - [x] POST 부스 등록
  - [x] PUT 부스 수정
  - [x] DEL 부스 삭제
  - [x] (구현중) PUT 부스 운영상태 조정
- [x] 부스 메뉴
  - [x] POST 메뉴 추가
  - [x] GET 메뉴 목록 조회
  - [x] PUT 메뉴 수정
  - [x] DEL 메뉴 삭제
- [x] 부스 댓글
  - [x] GET 댓글 조회
  - [x] DEL 댓글 삭제
  - [x] POST 댓글 등록
- [x] 부스 좋아요
  - [x] POST 좋아요 트리거 (ON/OFF)
  - [x] GET 좋아요 갯수 조회
- [x] 공지사항
  - [x] GET 게시물 목록 조회
  - [x] GET 게시물 상세 조회
  - [x] POST 게시물 등록
  - [x] DEL 게시물 삭제
  - [x] GET 게시물 검색
  - [x] PUT 게시물 수정
- [x] 방명록
  - [x] POST 방명록 등록
  - [x] DELETE 방명록 삭제
  - [x] GET 방명록 조회
  - [x] POST 방명록 신고
- [x] 백오피스
  - [x] GET 신고된 방명록 조회
  - [x] GET 신고된 부스 댓글 조회
  - [x] ??? 그래프들
 
### STEP2. api-client.js에서 구현한 기능으로 컴포넌트에 API 연결하기

- [x] 부스
  - [x] 부스 목록 페이지
    - [x] 접속시 부스 목록 받아올 것
    - [x] 부스 생성 기능 만들 것
  - [x] 부스 상세 페이지
    - [x] 접속시 부스 상세 정보 받아올 것
    - [x] 부스 상세 정보 수정 기능 만들 것
    - [x] 부스 삭제 기능 만들 것
- [x] 부스 메뉴
  - [x] 부스 상세 페이지
    - [x] 접속시 부스 메뉴 정보 받아올 것
    - [x] 부스 메뉴 정보 추가/수정/삭제 기능 만들 것
- [x] 부스 좋아요
  - [x] 부스 상세 페이지
    - [x] 접속시 부스 좋아요 갯수 받아올 것
    - [x] 부스 좋아요 ON/OFF 기능 만들 것
- [x] 부스 댓글
  - [x] 부스 상세 페이지
    - [x] 접속시 부스 댓글 정보 받아올 것
    - [x] 부스 댓글 작성 기능 만들 것
    - [x] 부스 댓글 신고 기능 만들 것
    - [x] 부스 댓글 삭제 기능 만들 것
- [x] 공지사항
  - [x] 공지사항 페이지
    - [x] 접속시 공지사항 목록 받아올 것
    - [x] 공지사항 클릭시 상세 정보 받아올 것
    - [x] 공지사항 추가 기능 만들 것
    - [x] 공지사항 수정 기능 만들 것
    - [x] 공지사항 삭제 기능 만들 것
- [x] 방명록
  - [x] 방명록 페이지
    - [x] 접속시 댓글 정보 받아올 것
    - [x] 댓글 작성 기능 만들 것
    - [x] 댓글 신고 기능 만들 것
    - [x] 댓글 삭제 기능 만들 것

### STEP3. API 오류 처리 및 코드 리팩토링

**Comment by PortalCube** [comment]
이제 이미지랑 로그인 남았는데 각 이슈에서 해결하겠습니다.
