### ISSUE TITLE
feat: API를 "진짜로" 연결하기

### ISSUE THREAD

**Issue by PortalCube** [Hallym-LIKELION/HallymFestival2023-Frontend#45]
# TODO

- [x] Step.1 부스 API
- [x] Step.2 공지사항 API
- [x] Step.3 방명록 API
- [ ] Step.4 백오피스 API

이번주 수요일까지 끝내보겠습니다.

**Comment by PortalCube** [comment]
완료
