### ISSUE TITLE
feat: 다른 페이지에도 Modal 적용 시키기 

### ISSUE THREAD

**Issue by PortalCube** [Hallym-LIKELION/HallymFestival2023-Frontend#8]
# TODO
- [x] 방명록 작성에 Modal 적용시키기
- [x] 방명록 삭제에 Modal 적용시키기
- [x] 공지사항 작성에 Modal 적용시키기
- [x] 공지사항 수정에 Modal 적용시키기
- [x] 부스 상세 페이지 - 부스 생성에 Modal 적용시키기
- [x] 부스 상세 페이지 - 부스 수정에 Modal 적용시키기
- [x] 부스 상세 페이지 - 댓글 삭제에 Modal 적용시키기
- [ ] 프로그램 목록 - 프로그램 보기에 Modal 적용시키기
- [x] Modal 컴포넌트 코드 정리하기

**Comment by PortalCube** [comment]
완료
